In [107]:
import pandas as pd 
from selenium import webdriver
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import pandas as pd

In [111]:
# Function to scrape rest days data from nbastuffer.com

def rest_days_scrape(year):    
    url = f'https://www.nbastuffer.com/{year}-nba-rest-days-stats/'

    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    table = soup.find_all("table")[0]

    data = [[cell.text for cell in row.find_all(["th","td"])]
                            for row in table.find_all("tr")]
    df = pd.DataFrame(data)

    df.columns = df.iloc[0,:]
    df.drop(index=0,inplace=True)
    return df 

# Pull data 
rest_17_18 = rest_days_scrape('2017-2018')
rest_18_19 = rest_days_scrape('2018-2019')
rest_19_20 = rest_days_scrape('2019-2020')

# Add year column
rest_17_18['Year'] = '2017-2018'
rest_18_19['Year'] = '2018-2019'
rest_19_20['Year'] = '2019-2020'

# Concat 1 dataframe
frames = [rest_17_18,rest_18_19,rest_19_20]
rest_days = pd.concat(frames)
rest_days.columns

# drop columns
rest_days.drop(columns=['RANK','OPPONENT', 'OPPONENT\nTODAY'], inplace=True)

# rename columns
rest_days.rename(columns={'TEAM NAME': 'Team',
                  '3IN4-B2B\nGP3IN4-B2B Games PlayedTotal number of games played in (3rd game -also played yesterday- in 4 nights) situation':'3in4_BTB',
                  '3IN4-B2B\nW%3IN4-B2B Games Winning PercentagePercentage of games won played in (3rd game -also played yesterday- in 4 nights) situation':'3in4_BTB_W%',
                 '3IN4-B2B\nAED3IN4-B2B Games Adjusted Efficiency DifferentialEfficiency differential in (3rd game -also played yesterday- in 4 nights) situation':'3in4_BTB_DIFF',
                 'B2B\nGPB2B Games PlayedTotal number of games played in (back-to-back) situation':'BTB',
                 'B2B\nW%B2B Games Winning PercentagePercentage of games won played in (back-to-back) situation':'BTB_W%',
                 'B2B\nAEDB2B Games Adjusted Efficiency DifferentialEfficiency differential in the (back-to-back) situation':'BTB_DIFF',
                 '3IN4\nGP3IN4 Games PlayedTotal number of games played in (3rd game in 4 nights) situation':'3in4',
                 '3IN4\nW%3IN4 Games Winning PercentagePercentage of games won played in (3rd game in 4 nights) situation':'3in4_W%',
                 '3IN4\nAED3IN4 Games Adjusted Efficiency DifferentialEfficiency differential in the (3rd game in 4 nights) situation':'3in4_DIFF',
                 '1 DAY\nGP1 DAY Games PlayedTotal number of games played in (having one day rest) situation':'one_day_rest',
                 '1 DAY\nW%1 DAY Games Winning PercentagePercentage of games won played in (having one day rest) situation':'one_day_rest_w%',
                 '1 DAY\nAED1 DAY Games Adjusted Efficiency DifferentialEfficiency differential in the (having one day rest) situation':'one_day_rest_diff',
                 '2 DAYS\nGP2 DAYS Games PlayedTotal number of games played in (having two days rest) situation':'two_day_rest',
                 '2 DAYS\nW%2 DAYS Games Winning PercentagePercentage of games won played in (having two days rest) situation':'two_day_rest_w%',
                 '2 DAYS\nAED2 DAYS Games Adjusted Efficiency DifferentialEfficiency differential in the (having two days rest) situation':'two_day_rest_diff',
                 '3+ DAYS\nGP3+ DAYS Games PlayedTotal number of games played in (having three or more days rest) situation':'three_plus_rest',
                 '3+ DAYS\nW%3+ DAYS Games Winning PercentagePercentage of games won played in (having three or more days rest) situation':'three_plus_rest',
                 '3+ DAYS\nAED3+ DAYS Games Adjusted Efficiency DifferentialEfficiency differential in the (having three or more days rest) situation':'three_plus_rest'},
                 inplace=True)

# save to csv 
rest_days.to_csv('data/rest_days.csv')

rest_days.head()

,Team,3in4_BTB,3in4_BTB_W%,3in4_BTB_DIFF,BTB,BTB_W%,BTB_DIFF,3in4,3in4_W%,3in4_DIFF,one_day_rest,one_day_rest_w%,one_day_rest_diff,two_day_rest,two_day_rest_w%,two_day_rest_diff,three_plus_rest,three_plus_rest,three_plus_rest,Year
1,Atlanta,12,0.167,-15.1,3,0.000,-15.6,8,0.500,-8.3,41,0.293,-7.4,13,0.308,-9.9,5,0.400,-8.5,2017-2018
2,Boston,10,0.700,2.4,3,0.333,-7.8,10,0.800,5.6,40,0.725,5.8,13,0.462,0.7,5,0.600,8.4,2017-2018
3,Brooklyn,7,0.286,-14.7,8,0.250,-11.9,10,0.400,-9.4,33,0.364,-5.8,20,0.350,-9.0,3,0.333,-5.7,2017-2018
4,Charlotte,11,0.364,-1.3,3,0.333,-4.2,11,0.636,2.1,41,0.463,0.5,10,0.400,4.3,6,0.167,-6.3,2017-2018
5,Chicago,10,0.200,-16.8,4,0.250,-23.9,9,0.444,-10.2,39,0.359,-9.6,14,0.357,-13.7,5,0.200,-14.9,2017-2018